name: NPM Release

on:
  workflow_dispatch:

  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18.18.2'
          registry-url: 'https://registry.npmjs.org'

      - name: Setup Git
        run: |
          git config user.name "lb-infra gh-action"
          git config user.email "lb-infra@gh-action.none"
          git config advice.addIgnoredFile false

      - name: Install dependencies and build 🔧
        run: |
          date > generated.log
          yarn install
          yarn rebuild
          git add dist generated.log
          git commit -m "Rebuild latest src"
          git push

      - name: Publish package on NPM 📦
        # run: npm publish
        run: echo "PUBLISH"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
