name: NPM Release

on:
  workflow_dispatch:
    inputs:
      build_mode:
        type: choice
        description: Build Mode (patch | minor | major)
        options:
          - patch
          - minor
          - major

  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18.18.2'
          registry-url: 'https://registry.npmjs.org'

      - name: Setup Git
        run: |
          git config user.name "lb-infra gh-action"
          git config user.email "lb-infra@gh-action.none"
          git config advice.addIgnoredFile false
          git config advice.detachedHead false

      - name: Install dependencies and build 🔧
        run: |
          date > built_generated
          yarn install
          yarn rebuild:${{ github.event.inputs.name }}

          VERSION=$(jq -r .version package.json)
          GIT_TAG="v$VERSION"

          if [ $(git tag --list | egrep -q $GIT_TAG) ];
          then
            echo "Tag $GIT_TAG existed!"
          else
            git tag $GIT_TAG
          fi

          git checkout $GIT_TAG

          git add built_generated
          git commit -m "Rebuild latest src"
          git push origin $GIT_TAG

      - name: Publish package on NPM 📦
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
